on:
    push:
      branches:
        - main
      paths:
        - 'src/**'
        # - '!src/tests/**'
jobs:
    cicd:
      runs-on: ubuntu-latest
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        LAMBDA_URL: https://bzhlvvvs.com
        TITLE: "@bzhlvvvs"
        FAVICON_URL: https://personal-misho.s3.eu-north-1.amazonaws.com/favicon.ico
        PLAYLIST_ID: 4qw4F3Mi3eGjXwLeKM5pYx
        LINKEDIN: https://www.linkedin.com/me/mbozhilov/
        GITHUB: https://github.com/asynchroza/bzhlvvvs-spotify
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-north-1
  
        - run: make pipeline-deploy